#!/usr/bin/env bash
set -e

if [[ "${#}" -ne "1"  ]]; then
    echo "  This script takes one argument:"
    echo "    - install configuration file"
    echo "    - directory with configuration files"
    echo
    exit 1
fi

if [[ -f "${1}" ]]; then
    CONFIGS=(${1})
elif [[ -d "${1}" ]];then
    CONFIGS=($(find $1 -type f | tr '\n' ' '))
fi

DOTBOT_DIR="tools/dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

for config in ${CONFIGS[*]}; do
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${config}" -v
done

