#!/bin/bash

function pre_commit_disable {
    repo_root="$(git rev-parse --show-toplevel)"
    for file in {pre-commit,commit-msg}; do
        chmod -x "${repo_root}/.git/hooks/${file}"
    done
}

function pre_commit_enable {
    repo_root="$(git rev-parse --show-toplevel)"
    for file in {pre-commit,commit-msg}; do
        chmod +x "${repo_root}/.git/hooks/${file}"
    done
}
