- clean: ['~']

- shell:
  - [sleep 0, Installing krzysztofromanowski94's dev machine dotfiles]
  -
    command: [git pull, Updating dotfiles]
    stdout: true
    stderr: true
  -
    command: [git submodule update --init --recursive, Installing submodules]
    stdout: true
    stderr: true

- link:
    ~/.tmux:
      force: true
      path: tmux
    ~/.tmux.conf:
      force: true
      path: tmux/tmux.conf

- shell:
  -
    command: [ansible-playbook ./playbooks/install-tmux.yml, Installing TMUX]
    stdout: true
    stderr: true
  - tmux start-server
  - tmux new-session -d
  -
    command: [~/.tmux/plugins/tpm/scripts/install_plugins.sh, Installing TMUX plugins]
    stdout: true
    stderr: true
  - tmux kill-server

