- clean: ['~']

- shell:
  - [sleep 0, Installing krzysztofromanowski94's dev machine dotfiles]
  -
    command: [git pull, Updating dotfiles]
    stdout: true
    stderr: true
  -
    command: [git submodule update --init --recursive, Installing submodules]
    stdout: true
    stderr: true
  -
    command: [./scripts/prepare-dev-machine.sh, Configuring development machine]
    stdout: true
    stderr: true
- link:
    ~/.tmux:
      force: true
      path: tmux
    ~/.tmux.conf:
      force: true
      path: tmux/tmux.conf

  
- shell:
  -
    command: [~/.tmux/tmp/scripts/install_plugins.sh, Installing TMUX plugins]
    stdout: true
    stderr: true

    
