- clean: ['~']

- shell:
  - [sleep 0, Installing krzysztofromanowski94's dev machine dotfiles]
  -
    command: [./scripts/prepare-dev-machine.sh, Configuring development machine]
    stdout: true
    stderr: true
