- clean: ['~']

- shell:
  - [sleep 0, Installing krzysztofromanowski94's dev machine dotfiles]
  -
    command: [./scripts/prepare-dev-machine.sh, Configuring development machine]
    stdout: true
    stderr: true
- link:
    ~/.tmux:
      force: true
      path: tmux
  
- shell:
  -
    command: [~/.tmux/tmp/scripts/install_plugins.sh, Installing TMUX plugins]
    stdout: true
    stderr: true

    
