- clean: ['~']

- shell:
  - [sleep 0, Installing krzysztofromanowski94's workers dotfiles]
  -
    command: [git pull, Updating dotfiles]
    stdout: true
    stderr: true
  -
    command: [git submodule update --init --recursive, Installing submodules]
    stdout: true
    stderr: true
  -
    command: [./scripts/get-completion-files.sh, Downloading bash-completion files]
    stdout: true
    stderr: true

- link:
    ~/.vim:
      force: true
      path: vim/conf/
    ~/.vimrc:
      force: true
      path: vim/.vimrc
    ~/.bash_completion:
      force: true
      path: bash-completion/bash_completion
    ~/.bash_completion.d:
      force: true
      path: bash-completion/bash_completion.d
    ~/.gitconfig:
      force: true
      path: git/.gitconfig
    ~/.gitconfig.local:
      force: true
      path: git/.gitconfig.local

- shell:
  -
    command: [mkdir ~/.vim/autoload]
    stdout: true
    stderr: true
  -
    command: ["wget https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim -O ~/.vim/autoload/plug.vim -o /dev/null", get autoload/plug.vim]
    stdout: true
    stderr: true
