---
- name: install tmux dependencies
  hosts: localhost
  become: yes
  tasks:
    - name: install tmux dependencies (CentOS || RHEL)
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - ncurses-dev
        - libevent-dev
      when: >
        ansible_distribution == 'CentOS' or
        ansible_distribution == 'Red Hat Enterprise Linux'


    - name: install tmux dependencies (Fedora)
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - ncurses-devel
        - libevent-devel
      when: >
        ansible_distribution == 'Fedora'

    - name: install tmux dependencies (Archlinux)
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - ncurses
        - libevent
      when: ansible_distribution == 'Archlinux'

    - name: install build dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - automake
        - autoconf
        - autogen
        - gcc
        - pkg-config
        - make

- name: install tmux
  hosts: localhost
  tasks:
    - name: git clone tmux repository
      git:
        repo: 'https://github.com/tmux/tmux.git'
        dest: ../tmux/repository

    - name: autogen
      command: ./autogen.sh
      args:
        chdir: ../tmux/repository

    - name: configure
      command: ./configure
      args:
        chdir: ../tmux/repository

    - name: make
      command: make
      args:
        chdir: ../tmux/repository

    - name: make install
      become: yes
      command: make install
      args:
        chdir: ../tmux/repository

