---
- name: install vagrant
  hosts: localhost
  become: yes
  tasks:
    - name: install vagrant dependencies (Archlinux)
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - libvirt
        - qemu
        - vagrant
        - gcc
        - make
        - bridge-utils
        - dmidecode
        - dnsmasq
        - ebtables
        - pkg-config
      when: ansible_distribution == 'Archlinux'

    - name: enable and start libvirtd
      systemd:
        name: libvirtd
        enabled: yes
        state: started

    - name: install vagrant plugins
      shell: |
        #!/bin/bash
        set -xe
        vagrant plugin install pkg-config
        # workaround from https://wiki.archlinux.org/index.php/Vagrant#vagrant-libvirt
        CONFIGURE_ARGS='with-ldflags=-L/opt/vagrant/embedded/lib with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib' \
          GEM_HOME=~/.vagrant.d/gems GEM_PATH=$GEM_HOME:/opt/vagrant/embedded/gems PATH=/opt/vagrant/embedded/bin:$PATH \
          vagrant plugin install vagrant-libvirt


