---
- name: install vagrant-libvirt
  hosts: localhost
  become: yes
  tasks:
    - name: build-dep for Vagrant (Ubuntu)
      command: apt-get build-dep -y vagrant ruby-libvirt
      warn: False
      when: ansible_distribution == 'Ubuntu'

    - name: libvirt (Ubuntu)
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - qemu
        - qemu-kvm
        - libvirt-bin
        - ebtables
        - dnsmasq-base
      when: ansible_distribution == 'Ubuntu'

    - name: dev packages (Ubuntu)
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - libxslt-dev
        - libxml2-dev
        - libvirt-dev
        - zlib1g-dev
        - ruby-dev
      when: ansible_distribution == 'Ubuntu'

    - name: ensure libvirt groups exists
      group:
        name: libvirt
        state: present

    - name: add current user to libvirt group
      user:
        name: "{{ ansible_user_id }}"
        append: yes
        groups: libvirt

    - name: enable and start libvirtd
      systemd:
        name: libvirtd
        enabled: yes
        state: started
      when: ansible_distribution == 'Archlinux'

    - name: vagrant-libvirt plugin
      become: no
      command: vagrant plugin install vagrant-libvirt
