---
- name: install awesome wm
  hosts: localhost
  become: yes
  tasks:
    - name: install common awesome wm dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - xorg
        - xorg-xinit
        - awesome

      when: ansible_distribution == 'Archlinux'

    - name: Archlinux
      package:
        name: "{{ item }}"
        state: present
      with_items:
      when: ansible_distribution == 'Archlinux'

    - name: Fedora
      package:
        name: "{{ item }}"
        state: present
      with_items:
      when: ansible_distribution == 'Fedora'

    - name: CentOS || RHEL
      package:
        name: "{{ item }}"
        state: present
      with_items:
      when: >
        ansible_distribution == 'CentOS' or
        ansible_distribution == 'Red Hat Enterprise Linux'

