---
- name: install packages for worker machine
  hosts: localhost
  become: yes
  tasks:
    - name: common packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        # TODO: change vim installation to source from repository
        # - vim
        - bash-completion
        - ShellCheck
