---
- name: install packages for worker machine
  hosts: localhost
  become: yes
  tasks:
    - name: common packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - vim-nox
        - bash-completion

